name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest coverage

    - name: Add src to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:src" >> $GITHUB_ENV

    - name: Run tests with coverage
      run: |
        coverage run --source=src/HyperShperes -m unittest discover -s tests
        coverage report --fail-under=75

    - name: Upload coverage HTML (optional)
      if: success()
      run: |
        coverage html
        echo "View HTML report in htmlcov/index.html"
